### ISSUE TITLE
Uploading from local file doesn't work - http error 403

### ISSUE THREAD

**Issue by sergeyastakhov** [hotosm/oam-uploader#85]
When trying upload image from local file, the upload process is stuck with the message "Uploading 1 image (0%)."
In browser log there is repeating requests to the oam-uploader-production-temp.s3.amazonaws.com host with results 403 error responses with following content:

```xml
<Error>
<Code>AccessForbidden</Code>
<Message>CORSResponse: This CORS request is not allowed. This is usually because the evalution of Origin, request method / Access-Control-Request-Method or Access-Control-Request-Headers are not whitelisted by the resource's CORS spec.</Message>
<Method>POST</Method>
<ResourceType>UPLOADS</ResourceType>
<RequestId>2EB24734888B1875</RequestId>
<HostId>OiXu8fDkeQAkCMUDSIPIpHzNsKq6giuF9ExVRVDXV+f/M0zlgYZB456z5nW6K12kB211BwwAyG4=</HostId>
</Error>
```

**Comment by smit1678** [comment]
@sergeyastakhov This should be fixed now. There was an issue in our configuration that was not updated based on the last deployment.

**Comment by sergeyastakhov** [comment]
The error message is changed (now it is "400 Bad request"), but upload still doesn't working.

```xml
<Error>
<Code>AuthorizationHeaderMalformed</Code>
<Message>The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.</Message>
<RequestId>F0C6E6DD00A1FE4D</RequestId>
<HostId>Xmhd5zppz7Lt+VgtCelt7gj4XdycbKIlGKzJmHg6hGG1UAGyvMPjwRnk8EToeiDkdWptje76Dws=</HostId>
</Error>
```
